### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by mikeseeh** [MarcelLehmann/Lohnsteuer#1]
Hallo!

Interessantes Projekt - Danke!
Unter welcher Lizenz steht der Source Code?
Kann er frei verwendet werden?

Bitte im README angeben …

**Comment by MarcelLehmann** [comment]
Vielen Dank, ich habe den Code nun unter die Apache Lizenz 2.0 gestellt.

**Comment by mikeseeh** [comment]
Danke!
