### ISSUE TITLE
Code wird automatisch aus dem Programmablaufplan vom BMF erzeugt.

### ISSUE THREAD

**Issue by riedelmax** [MarcelLehmann/Lohnsteuer#2]

**Comment by MarcelLehmann** [comment]
Hallo,

das BMF stellt Pseudocode im XML-Format bereit. Siehe z.B. für 2017: https://www.bmf-steuerrechner.de/pruefdaten/Lohnsteuer2017.xml <https://www.bmf-steuerrechner.de/pruefdaten/Lohnsteuer2017.xml>. Die Klasse Generator.java in meinem Projekt parst diese Dateien und erzeugt daraus dann den Java-Code.

Viele Grüße
Marcel
